[package]
name = "roundedcorners"
version = "0.0.4"

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "1.2.4", features = ["system-tray", "window-set-position"] }
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
winapi = { version = "0.3.9", features = ["winuser"] }

[features]
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "monitors"
path = "src/lib/main.rs"
