[package]
name = "roundedcorners"
version = "0.0.1"
description = "Rounded Corners"
authors = ["Nikola Hristov <nikola@lightrix.dev>"]
license-file = "LICENSE"
repository = "https://github.com/RoundedCorners/app"
default-run = "roundedcorners"
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
wry = { path = ""}
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.5", features = ["system-tray", "window-set-position"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
