[package]
name = "roundedcorners"
version = "0.0.4"

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
regex = "1.7.1"
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
tauri = { version = "1.2.4", features = ["system-tray", "window-set-ignore-cursor-events", "window-set-position"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
