[package]
name = "roundedcorners"
version = "0.0.1"

[build-dependencies]
tauri-build = { version = "1.1.1", features = [] }

[dependencies]
wry = { path = "../../wry" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.1.1", features = ["system-tray", "window-set-position"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
