[package]
name = "roundedcorners"
version = "0.0.5"

[build-dependencies]
tauri-build = { path = "../../../withpatches/tauri/core/tauri-build", features = [] }

[dependencies]
regex = "1.8.1"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
tauri = { path = "../../../withpatches/tauri/core/tauri", features = ["system-tray", "window-set-ignore-cursor-events", "window-set-position"] }
tauri-plugin-store = { path = "../../plugins-workspace/plugins/store" }

[features]
custom-protocol = ["tauri/custom-protocol"]
