[package]
name = "roundedcorners"
version = "0.0.4"

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { git = "https://github.com/withpatches/tauri", branch = "click-through-windows", features = ["api-all", "system-tray"] }
tauri-plugin-store = { git = "https://github.com/roundedcorners/plugins-workspace", branch = "main" }
winapi = { version = "0.3.9", features = ["winuser"] }

[features]
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "monitors"
path = "src/lib/monitors.rs"

