[package]
name = "roundedcorners"
version = "0.0.2"

[build-dependencies]
tauri-build = { version = "1.1.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { git = "https://github.com/withpatches/tauri", branch = "click-through", features = ["system-tray", "window-set-position"] }
tauri-plugin-store = { path = "../../tauri-plugin-store" }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
