[package]
name = "roundedcorners"
version = "0.0.5"

[build-dependencies]
tauri-build = { version = "1.3.0", features = [] }

[dependencies]
regex = "1.8.4"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
tauri = { version = "1.3.0", features = ["api-all", "system-tray"] }
tauri-plugin-store = { path = "../../plugins-workspace/plugins/store" }

[features]
custom-protocol = ["tauri/custom-protocol"]
