version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase
    - package-ecosystem: "cargo"
      directory: "/src-tauri/"
      schedule:
          interval: "daily"
      versioning-strategy: increase
