name: CrabNebula

concurrency:
    group: CrabNebula-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    Release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.2

            - uses: crabnebula-dev/cloud-release@dev
              with:
                  command: release draft ${{ secrets.CN_APP_ID }} 0.1.0
                  api-key: ${{ secrets.CN_API_KEY }}
