on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14, 16, 18]
        steps:
            - uses: actions/checkout@v3.1.0
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
              working-directory: .
            - run: npm run build
              working-directory: .
