on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ["latest"]

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.3
              with:
                  version: 7.13.4
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - run: pnpm install
            - run: npm shrinkwrap
            - run: npm ci
            - run: pnpm run build --if-present
