on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]

        steps:
            - uses: actions/checkout@v3.1.0
            - uses: pnpm/action-setup@v2.2.3
              with:
                  version: 7.13.4
            - uses: actions/setup-node@v3.5.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"


            - run: pnpm install --frozen-lockfile
              working-directory: /
            - run: pnpm run build --if-present
              working-directory: /

