on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14, 16, 18]
        steps:
            - uses: actions/checkout@v3.1.0
            - uses: pnpm/action-setup@v2.2.3
              with:
                  version: 7.13.4
                  run_install: |
                      - recursive: true
                        args: [
                          --shamefully-hoist=true,
                          --child-concurrency=9999,
                          --network-concurrency=9999,
                          --prefer-frozen-lockfile=false,
                          --strict-peer-dependencies=false,
                          --unsafe-perm=true,
                          --lockfile-only
                        ]
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: ${{ matrix.node-version }}
                  check-latest: true
                  cache: "pnpm"
                  cache-dependency-path: './pnpm-lock.yaml'
            - run: pnpm install
              working-directory: .
            - run: pnpm run build
              working-directory: .
