name: Rust

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                toolchain: ["stable", "nightly"]
        steps:
            - uses: actions/checkout@v3.1.0
            - uses: actions-rs/toolchain@v1.0.3
              with:
                  profile: minimal
                  toolchain: ${{ matrix.toolchain }}

            - uses: actions-rs/cargo@v1.0.3
              with:
                command: build
                args: --release --all-features --manifest-path ./src-tauri/Cargo.toml
