name: Tauri

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    prepare:
        uses: roundedcorners/app/.github/workflows/node.yml@main

    build:
        needs: prepare
        strategy:
            matrix:
                toolchain: ["stable", "nightly"]
                platform: ["windows-latest"]
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v3.1.0
            - uses: actions-rs/toolchain@v1.0.3
              with:
                  profile: minimal
                  toolchain: ${{ matrix.toolchain }}
            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key:
                      ${{ runner.os }}-cargo-${{
                      hashFiles('./src-tauri/Cargo.toml') }}
            - uses: actions/download-artifact@v3
              id: download
              with:
                  name: node-18-dist-.
                  path: .
            - run: echo ${{steps.download.outputs.download-path}}
            - uses: actions-rs/cargo@v1.0.3
              with:
                  command: build
                  args:
                      --release --all-features --manifest-path
                      ./src-tauri/Cargo.toml
