name: Rust

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        strategy:
            matrix:
                toolchain: ["stable", "nightly"]
                platform: ["windows-latest"]
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v3.1.0
            - uses: actions-rs/toolchain@v1.0.3
              with:
                  profile: minimal
                  toolchain: ${{ matrix.toolchain }}
            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key:
                      ${{ runner.os }}-cargo-${{
                      hashFiles('./src-tauri/Cargo.toml') }}
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
            - uses: actions-rs/cargo@v1.0.3
              with:
                  command: build
                  args:
                      --release --all-features --manifest-path
                      ./src-tauri/Cargo.toml
